
--Ispiši sve studente koji nisu na petoj godini
  
SELECT JMBAG,
    IME || ' ' || PREZIME "Student",
    GODINA "Godina"
FROM STUDENTI
WHERE GODINA < 5
ORDER BY PREZIME;



--Ispiši informacije o predmetima i profesorima

SELECT PREDMETI.PREDMET "Predmet",
    PREDMETI.SIFRA "Šifra",
    PREDMETI.OBV_IZB "Obvezni/Izborni",
    PROFESORI.TITULA || ' ' || PROFESORI.IME || ' ' || PROFESORI.PREZIME "Profesor",
    PREDMETI.ETSC "ETSC Bodova",
    PREDMETI.GODINA "Godina"
FROM PREDMETI
    RIGHT JOIN PROFESORI ON PREDMETI.ID_PROF = PROFESORI.ID_PROFESOR
ORDER BY PREDMETI.PREDMET;



--Ispiši sve profesore koji nisu sa ketedre informatika

SELECT PROFESORI.TITULA || ' ' || PROFESORI.IME || ' ' || PROFESORI.PREZIME "Profesor",
    KATEDRE.KATEDRE "Katedra"
FROM KATEDRE
    INNER JOIN PROFESORI ON KATEDRE.ID_KATEDRE = PROFESORI.ID_KAT
WHERE KATEDRE.KATEDRE NOT LIKE 'INFORMATIKA'
ORDER BY KATEDRE.KATEDRE;



--Ispiši sve predmete koji se pišu 1.2.2017

SELECT PREDMETI.PREDMET "Predmet",
    TERMINI.ROK_DATUM "Datum roka",
    TERMINI.ROK_VRIJEME "Vrijeme ispita",
    TERMINI.ROK_DVORANA "Dvorana"
FROM PREDMETI
    RIGHT JOIN TERMINI ON PREDMETI.ID_PREDMET = TERMINI.ID_PREDMET
WHERE TERMINI.ROK_DATUM = '01.02.2017'
ORDER BY PREDMETI.PREDMET;



--Ispiši sve studente koji su prijavili rok

SELECT STUDENTI.JMBAG,
    STUDENTI.IME || ' ' || STUDENTI.PREZIME "Student",
    PREDMETI.PREDMET "Predmet",
    PRIJAVA.IZLAZAK "Broj izlaska",
    TERMINI.ROK_DATUM "Datum ispita",
    TERMINI.ROK_VRIJEME "Vrijeme ispita",
    TERMINI.ROK_DVORANA "Dvorana"
FROM (
        (
            STUDENTI
            LEFT JOIN PRIJAVA ON STUDENTI.JMBAG = PRIJAVA.JMBAG
        )
        LEFT JOIN TERMINI ON PRIJAVA.ID_ISPITTERMIN = TERMINI.ID_TERMINI
    )
    LEFT JOIN PREDMETI ON PRIJAVA.ID_PREDMET = PREDMETI.ID_PREDMET
WHERE PREDMETI.PREDMET IS NOT NULL
ORDER BY STUDENTI.PREZIME;

--Ispiši sve rokove predmeta Upravljanje podacima.
SELECT PREDMETI.PREDMET "Predmet",
    TERMINI.ROK_DATUM "Datum roka",
    TERMINI.ROK_VRIJEME "Vrijeme ispita",
    TERMINI.ROK_DVORANA "Dvorana"
FROM PREDMETI
    RIGHT JOIN TERMINI ON PREDMETI.ID_PREDMET = TERMINI.ID_PREDMET
WHERE PREDMETI.PREDMET = 'Upravljanje podacima';

